### ISSUE TITLE
Stopped working on Twitch VODs

### ISSUE THREAD

**Issue by ke-d** [nkestrel/mediaurltimestamper#2]
Seems like they changed their domain to `go.twitch.tv`.

**Comment by nkestrel** [comment]
Thanks for the report, it appears to work for me though (FF56 & FF58), do you have any specific examples?

The extension is already enabled for all twitch subdomains so `go.twitch.tv` shouldn't stop it from working. The `#t` page action appears in the location bar and clicking it updates the timestamp. Clearing history and loading a timestamped url in a new tab starts the video at the specified timestamp.

Remember default settings require the video to be longer than 10 minutes to apply automatic timestamp and it is removed in the first or last 2 minutes.

**Comment by ke-d** [comment]
Huh, it wasn't working for the past couple of days and today it looks like twitch fixed something on their end. Anyways sorry for the noise.
