### ISSUE TITLE
Add the "pided" youtube frontent

### ISSUE THREAD

**Issue by sxe** [nkestrel/mediaurltimestamper#8]
Hi, 
I use https://github.com/TeamPiped/Piped as a youtube frontend which is a better working invidious imo.
There are not as many instances yet but the main instance works pretty great.
I would love to see support for those instances.

I would suggest to not add a hard coded instance but add a way to choose a specific instance in the settings.
Updating a list of instance might be to much work, so maybe a textfield in the settings where you add/can change the url would be the best option. (This would also be very useful for the invidious instances).
The extension  https://github.com/SimonBrazell/privacy-redirect already does something similar, so it could be used as an example.

Cheers

**Comment by nkestrel** [comment]
Thanks for the suggestion, added in 6bde732f162a0afcc70df8f7484f681104f78934.

**Comment by sxe** [comment]
Hey, thanks for adding this feature but unfortunately it doesn't seem to work for me.
I just installed the latest firefox version and neither invidious nor piped work. When I visit a video page it doesn't even show the icon in the url bar. It works on normal youtube pages tho. Am I missing something? Do I have to enable it somehow?

*edit: Now it works. Not sure what exactly happened. The addon might have bin disabled cause of new permissions but firefox didn't show it before.  

Greetings

**Comment by nkestrel** [comment]
Glad to hear you got it working. If you have a previous version installed, it won't update until you consent to the new website permissions.
